### PR TITLE
bump `sqlite-amalgamation` to `3.45.1`

### PR DESCRIPTION
**Pull request by etan-status**
- https://www.sqlite.org/releaselog/3_42_0.html
- https://www.sqlite.org/releaselog/3_43_0.html
- https://www.sqlite.org/releaselog/3_43_1.html
- https://www.sqlite.org/releaselog/3_43_2.html
- https://www.sqlite.org/releaselog/3_44_0.html
- https://www.sqlite.org/releaselog/3_44_1.html
- https://www.sqlite.org/releaselog/3_44_2.html
- https://www.sqlite.org/releaselog/3_45_0.html
- https://www.sqlite.org/releaselog/3_45_1.html

### CODE REVIEW

**Comment by arnetheduck** [comment]
tbh I'd wait for the .1 release ;)

**Comment by etan-status** [comment]
https://www.sqlite.org/chronology.html there is no .1 for 3.42.

Do you want to advance to latest in one go, or via 3.42.0 --> 3.43.2 --> 3.44.2? The intermediate versions have the advantage of it being easier to revert to them, at the cost of some extra CI / review time (for the additional 3.42.0 and 3.43.2 versions)

**Comment by arnetheduck** [comment]
latest is fine, as long as it's not a .0 .. haven't tracked every single version up to this point, don't really feel like maintaining that either

**Comment by arnetheduck** [comment]
that said, if you feel ambitious, one could create one commit per upstream and merge them all in one go with a fast-forward instead of squash

**Comment by arnetheduck** [comment]
in fact, the update.sh script could take care of the nimble bump _and_ the git commit as well similar to https://github.com/arnetheduck/nph/blob/master/format-git-repo.sh - as long as the commit is local, it can be amended should anything weird come up while making it

**Comment by etan-status** [comment]
Use merge/rebase instead of squash when accepting this one to preserve the intermediate versions.

**Pull request merged**
